name: CI
on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]

jobs:
  doCI:
    if: |
      (github.event_name == 'issue_comment' && github.event.issue.pull_request && github.event.comment.body == 'rebuild!') ||
      (github.event_name == 'pull_request') ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-22.04
    timeout-minutes: 35
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.AUTH_APP_ID }}
          private_key: ${{ secrets.AUTH_APP_CLIENT_KEY }}

      - name: Trigger Build in Private Repo
        uses: dacbd/create-issue-action@v1.2.1
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repo: demo-mixed-ci-private
          title: CheckPublicPR
          body: ${{ github.sha }}

#ToDo:
# on the rebuild! comment, there's an issue with the sha pointing to something other than pr/merge,
#     therefore, for 'rebuild!' we need to take the sha from github.event, and not github.sha

#ToDo:
# when the PR's source is a fork, we don't have access to secrets.
# this seems to be by design, as in public repos, anyone can create a fork.
